# SPDX-FileCopyrightText: 2022 The SMW Music Python Project Authors
# <https://github.com/com-posers-pit/smw_music/blob/develop/AUTHORS.rst>
#
# SPDX-License-Identifier: CC0-1.0

name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["develop"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER }}
          USERNAME: ${{ secrets.DEV_USER }}
          PORT: ${{ secrets.DEV_PORT }}
          KEY: ${{ secrets.DEV_SSHKEY }}
          script: |
            cd dev/smw_music
            git pull
            docker build -t smw_music --build-arg GITHASH=$(git rev-parse --short HEAD) .
            docker container rm -f smw_music
            docker container prune -f
            docker image prune -f
            docker run -dit --name smw_music -p 5000:80 smw_music
