# SPDX-FileCopyrightText: 2022 The SMW Music Python Project Authors
# <https://github.com/com-posers-pit/smw_music/blob/develop/AUTHORS.rst>
#
# SPDX-License-Identifier: CC0-1.0

name: Publish

on:
  push:
    tags: ['v*.*.*']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
          cache: 'poetry'
      - name: Install library
        run: poetry install --no-interaction
      - name: Run pyinstaller
        run: poetry run pyinstaller -F --hidden-import music21.alpha --hidden-import music21.audioSearch --hidden-import music21.configure --add-data "smw_music/data/mml.txt;smw_music/data" --add-data "smw_music/data/dashboard.ui;smw_music/data" --add-data "smw_music/data/ashtley.gif;smw_music/data" --add-data "smw_music/data/convert.bat;smw_music/data" --add-data "smw_music/data/convert.sh;smw_music/data" --add-data "smw_music/data/preferences.ui;smw_music/data" smw_music/scripts/dashboard.py
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dashboard.exe
          asset_name: beer-windows-$tag.exe
          tag: ${{ github.ref }}
          overwrite: true

  mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
          cache: 'poetry'
      - name: Install library
        run: poetry install --no-interaction
      - name: Run pyinstaller
        run: poetry run pyinstaller -F --hidden-import music21.alpha --hidden-import music21.audioSearch --hidden-import music21.configure --add-data "smw_music/data/mml.txt:smw_music/data" --add-data "smw_music/data/dashboard.ui;smw_music/data" --add-data "smw_music/data/ashtley.gif;smw_music/data" --add-data "smw_music/data/convert.bat;smw_music/data" --add-data "smw_music/data/convert.sh;smw_music/data" --add-data "smw_music/data/preferences.ui;smw_music/data" smw_music/scripts/dashboard.py
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dashboard
          asset_name: beer-osx-$tag
          tag: ${{ github.ref }}
          overwrite: true
